/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as DoencasRouteImport } from './routes/doencas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as ExamesIndexRouteImport } from './routes/exames.index'
import { Route as MedicosIndexRouteImport } from './routes/medicos.index'
import { Route as ExamesSlugIndexRouteImport } from './routes/exames.$slug.index'
import { Route as ExamesSlugTipoRouteImport } from './routes/exames.$slug.$tipo'
import { Route as MedicosEspIndexRouteImport } from './routes/medicos.$esp.index'
import { Route as MedicosEspDocRouteImport } from './routes/medicos.$esp.$doc'
import { Route as ExamesSlugAreaAreaRouteImport } from './routes/exames.$slug.area.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const DoencasRoute = DoencasRouteImport.update({
  id: '/doencas',
  path: '/doencas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesIndexRoute = ExamesIndexRouteImport.update({
  id: '/exames/',
  path: '/exames/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosIndexRoute = MedicosIndexRouteImport.update({
  id: '/medicos/',
  path: '/medicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesSlugIndexRoute = ExamesSlugIndexRouteImport.update({
  id: '/exames/$slug/',
  path: '/exames/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesSlugTipoRoute = ExamesSlugTipoRouteImport.update({
  id: '/exames/$slug/$tipo',
  path: '/exames/$slug/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosEspIndexRoute = MedicosEspIndexRouteImport.update({
  id: '/medicos/$esp/',
  path: '/medicos/$esp/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosEspDocRoute = MedicosEspDocRouteImport.update({
  id: '/medicos/$esp/$doc',
  path: '/medicos/$esp/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesSlugAreaAreaRoute = ExamesSlugAreaAreaRouteImport.update({
  id: '/exames/$slug/area/$area',
  path: '/exames/$slug/area/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/doencas': typeof DoencasRoute
  '/entrar': typeof EntrarRoute
  '/tratamentos': typeof TratamentosRoute
  '/exames/': typeof ExamesIndexRoute
  '/medicos/': typeof MedicosIndexRoute
  '/exames/$slug/$tipo': typeof ExamesSlugTipoRoute
  '/medicos/$esp/$doc': typeof MedicosEspDocRoute
  '/exames/$slug/': typeof ExamesSlugIndexRoute
  '/medicos/$esp/': typeof MedicosEspIndexRoute
  '/exames/$slug/area/$area': typeof ExamesSlugAreaAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/doencas': typeof DoencasRoute
  '/entrar': typeof EntrarRoute
  '/tratamentos': typeof TratamentosRoute
  '/exames': typeof ExamesIndexRoute
  '/medicos': typeof MedicosIndexRoute
  '/exames/$slug/$tipo': typeof ExamesSlugTipoRoute
  '/medicos/$esp/$doc': typeof MedicosEspDocRoute
  '/exames/$slug': typeof ExamesSlugIndexRoute
  '/medicos/$esp': typeof MedicosEspIndexRoute
  '/exames/$slug/area/$area': typeof ExamesSlugAreaAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/doencas': typeof DoencasRoute
  '/entrar': typeof EntrarRoute
  '/tratamentos': typeof TratamentosRoute
  '/exames/': typeof ExamesIndexRoute
  '/medicos/': typeof MedicosIndexRoute
  '/exames/$slug/$tipo': typeof ExamesSlugTipoRoute
  '/medicos/$esp/$doc': typeof MedicosEspDocRoute
  '/exames/$slug/': typeof ExamesSlugIndexRoute
  '/medicos/$esp/': typeof MedicosEspIndexRoute
  '/exames/$slug/area/$area': typeof ExamesSlugAreaAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar'
    | '/doencas'
    | '/entrar'
    | '/tratamentos'
    | '/exames/'
    | '/medicos/'
    | '/exames/$slug/$tipo'
    | '/medicos/$esp/$doc'
    | '/exames/$slug/'
    | '/medicos/$esp/'
    | '/exames/$slug/area/$area'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar'
    | '/doencas'
    | '/entrar'
    | '/tratamentos'
    | '/exames'
    | '/medicos'
    | '/exames/$slug/$tipo'
    | '/medicos/$esp/$doc'
    | '/exames/$slug'
    | '/medicos/$esp'
    | '/exames/$slug/area/$area'
  id:
    | '__root__'
    | '/'
    | '/adicionar'
    | '/doencas'
    | '/entrar'
    | '/tratamentos'
    | '/exames/'
    | '/medicos/'
    | '/exames/$slug/$tipo'
    | '/medicos/$esp/$doc'
    | '/exames/$slug/'
    | '/medicos/$esp/'
    | '/exames/$slug/area/$area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  DoencasRoute: typeof DoencasRoute
  EntrarRoute: typeof EntrarRoute
  TratamentosRoute: typeof TratamentosRoute
  ExamesIndexRoute: typeof ExamesIndexRoute
  MedicosIndexRoute: typeof MedicosIndexRoute
  ExamesSlugTipoRoute: typeof ExamesSlugTipoRoute
  MedicosEspDocRoute: typeof MedicosEspDocRoute
  ExamesSlugIndexRoute: typeof ExamesSlugIndexRoute
  MedicosEspIndexRoute: typeof MedicosEspIndexRoute
  ExamesSlugAreaAreaRoute: typeof ExamesSlugAreaAreaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doencas': {
      id: '/doencas'
      path: '/doencas'
      fullPath: '/doencas'
      preLoaderRoute: typeof DoencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/': {
      id: '/exames/'
      path: '/exames'
      fullPath: '/exames/'
      preLoaderRoute: typeof ExamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos/': {
      id: '/medicos/'
      path: '/medicos'
      fullPath: '/medicos/'
      preLoaderRoute: typeof MedicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/$slug/': {
      id: '/exames/$slug/'
      path: '/exames/$slug'
      fullPath: '/exames/$slug/'
      preLoaderRoute: typeof ExamesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/$slug/$tipo': {
      id: '/exames/$slug/$tipo'
      path: '/exames/$slug/$tipo'
      fullPath: '/exames/$slug/$tipo'
      preLoaderRoute: typeof ExamesSlugTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos/$esp/': {
      id: '/medicos/$esp/'
      path: '/medicos/$esp'
      fullPath: '/medicos/$esp/'
      preLoaderRoute: typeof MedicosEspIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos/$esp/$doc': {
      id: '/medicos/$esp/$doc'
      path: '/medicos/$esp/$doc'
      fullPath: '/medicos/$esp/$doc'
      preLoaderRoute: typeof MedicosEspDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/$slug/area/$area': {
      id: '/exames/$slug/area/$area'
      path: '/exames/$slug/area/$area'
      fullPath: '/exames/$slug/area/$area'
      preLoaderRoute: typeof ExamesSlugAreaAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  DoencasRoute: DoencasRoute,
  EntrarRoute: EntrarRoute,
  TratamentosRoute: TratamentosRoute,
  ExamesIndexRoute: ExamesIndexRoute,
  MedicosIndexRoute: MedicosIndexRoute,
  ExamesSlugTipoRoute: ExamesSlugTipoRoute,
  MedicosEspDocRoute: MedicosEspDocRoute,
  ExamesSlugIndexRoute: ExamesSlugIndexRoute,
  MedicosEspIndexRoute: MedicosEspIndexRoute,
  ExamesSlugAreaAreaRoute: ExamesSlugAreaAreaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
