/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamesIndexRouteImport } from './routes/exames.index'
import { Route as ExamesSlugIndexRouteImport } from './routes/exames.$slug.index'
import { Route as ExamesSlugTipoRouteImport } from './routes/exames.$slug.$tipo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesIndexRoute = ExamesIndexRouteImport.update({
  id: '/exames/',
  path: '/exames/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesSlugIndexRoute = ExamesSlugIndexRouteImport.update({
  id: '/exames/$slug/',
  path: '/exames/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesSlugTipoRoute = ExamesSlugTipoRouteImport.update({
  id: '/exames/$slug/$tipo',
  path: '/exames/$slug/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exames/': typeof ExamesIndexRoute
  '/exames/$slug/$tipo': typeof ExamesSlugTipoRoute
  '/exames/$slug/': typeof ExamesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exames': typeof ExamesIndexRoute
  '/exames/$slug/$tipo': typeof ExamesSlugTipoRoute
  '/exames/$slug': typeof ExamesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exames/': typeof ExamesIndexRoute
  '/exames/$slug/$tipo': typeof ExamesSlugTipoRoute
  '/exames/$slug/': typeof ExamesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exames/' | '/exames/$slug/$tipo' | '/exames/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exames' | '/exames/$slug/$tipo' | '/exames/$slug'
  id: '__root__' | '/' | '/exames/' | '/exames/$slug/$tipo' | '/exames/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamesIndexRoute: typeof ExamesIndexRoute
  ExamesSlugTipoRoute: typeof ExamesSlugTipoRoute
  ExamesSlugIndexRoute: typeof ExamesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/': {
      id: '/exames/'
      path: '/exames'
      fullPath: '/exames/'
      preLoaderRoute: typeof ExamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/$slug/': {
      id: '/exames/$slug/'
      path: '/exames/$slug'
      fullPath: '/exames/$slug/'
      preLoaderRoute: typeof ExamesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/$slug/$tipo': {
      id: '/exames/$slug/$tipo'
      path: '/exames/$slug/$tipo'
      fullPath: '/exames/$slug/$tipo'
      preLoaderRoute: typeof ExamesSlugTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamesIndexRoute: ExamesIndexRoute,
  ExamesSlugTipoRoute: ExamesSlugTipoRoute,
  ExamesSlugIndexRoute: ExamesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
